#!/usr/bin/env bash
# This script pings an IP address passed as an argument 5 times and checks if the host is on the network.

if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"
